### ISSUE TITLE
SWF file is not found

### ISSUE THREAD

**Issue by anmishael** [xjflyttp/yii2-jplayer-widget#1]
Aftre clean install it with next widget options:
echo xj\jplayer\VideoWidget::widget([
    'tagClass' => 'jp-video jp-video-360p',
    'skinAsset' => 'xj\jplayer\skins\BlueAssets',
    'mediaOptions' => [
        'm4v' => \yii\helpers\Url::toRoute(['file/download', 'id' => $model->primaryKey]),
    ],
    'jsOptions' => [
        'solution' => 'html, flash',
        'supplied' => "m4v",
        'wmode' => "window",
        'smoothPlayBar' => false,
        'keyEnabled' => true,
        'remainingDuration' => true,
        'toggleDuration' => true,
    ],
]);

404 error appeared:
assets/&lt;asset&gt;/Jplayer.swf not found
it fixes when i copy assets/js/Jplayer.swf to assets/ folder

**Comment by xjflyttp** [comment]
hi~
committed new revision.
you can try it .

**Comment by anmishael** [comment]
Thank you, just i'm using 2.7.0.2 (stable) version and your newest one give an error installation via composer:
xj/yii2-jplayer-widget dev-master requires bower-asset/jplayer 2.9.\* -> no matching package found.

so i simply fix it in 2.7.0.2 xj/yii2-jplayer-widget/JplayerWidget.php by changing line 137 from 
'swfPath' => $this->assetPublishDir, 
to 
'swfPath' => $this->assetPublishDir . '/js',
